"""initial schema

Revision ID: 06df84496ffb
Revises: 
Create Date: 2026-07-20 15:36:49.108314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06df84496ffb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_decision',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('review_cycle_id', sa.String(length=36), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_decision_review_cycle_id'), 'review_decision', ['review_cycle_id'], unique=False)
    op.create_table('sap_execution_package',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('technical_specification_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('sap_execution_repo_ref', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sap_execution_package_technical_specification_id'), 'sap_execution_package', ['technical_specification_id'], unique=False)
    op.create_index(op.f('ix_sap_execution_package_tenant_id'), 'sap_execution_package', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sap_execution_package_tenant_id'), table_name='sap_execution_package')
    op.drop_index(op.f('ix_sap_execution_package_technical_specification_id'), table_name='sap_execution_package')
    op.drop_table('sap_execution_package')
    op.drop_index(op.f('ix_review_decision_review_cycle_id'), table_name='review_decision')
    op.drop_table('review_decision')
    # ### end Alembic commands ###
