"""governance gates

Revision ID: 8ec61d70bfd9
Revises: 06df84496ffb
Create Date: 2026-07-20 16:32:28.290789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ec61d70bfd9'
down_revision: Union[str, None] = '06df84496ffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_gate_definition',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('gate_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('required_role', sa.String(length=64), nullable=False),
    sa.Column('allow_self_approval', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_gate_definition_gate_key'), 'approval_gate_definition', ['gate_key'], unique=False)
    op.create_index(op.f('ix_approval_gate_definition_tenant_id'), 'approval_gate_definition', ['tenant_id'], unique=False)
    op.create_table('gate_approval_request',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('gate_key', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=36), nullable=True),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('requested_by_role', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('decided_by_role', sa.String(length=64), nullable=True),
    sa.Column('decision_comments', sa.Text(), nullable=True),
    sa.Column('sod_violation', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gate_approval_request_entity_id'), 'gate_approval_request', ['entity_id'], unique=False)
    op.create_index(op.f('ix_gate_approval_request_gate_key'), 'gate_approval_request', ['gate_key'], unique=False)
    op.create_index(op.f('ix_gate_approval_request_tenant_id'), 'gate_approval_request', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_gate_approval_request_workflow_run_id'), 'gate_approval_request', ['workflow_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gate_approval_request_workflow_run_id'), table_name='gate_approval_request')
    op.drop_index(op.f('ix_gate_approval_request_tenant_id'), table_name='gate_approval_request')
    op.drop_index(op.f('ix_gate_approval_request_gate_key'), table_name='gate_approval_request')
    op.drop_index(op.f('ix_gate_approval_request_entity_id'), table_name='gate_approval_request')
    op.drop_table('gate_approval_request')
    op.drop_index(op.f('ix_approval_gate_definition_tenant_id'), table_name='approval_gate_definition')
    op.drop_index(op.f('ix_approval_gate_definition_gate_key'), table_name='approval_gate_definition')
    op.drop_table('approval_gate_definition')
    # ### end Alembic commands ###
