"""initial schema

Revision ID: 58c2924c6dd6
Revises: 
Create Date: 2026-07-20 15:36:48.586334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58c2924c6dd6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_cycle',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('artefact_type', sa.String(length=32), nullable=False),
    sa.Column('artefact_id', sa.String(length=36), nullable=False),
    sa.Column('gate', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_cycle_artefact_id'), 'review_cycle', ['artefact_id'], unique=False)
    op.create_index(op.f('ix_review_cycle_tenant_id'), 'review_cycle', ['tenant_id'], unique=False)
    op.create_table('review_comment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('review_cycle_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=64), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['review_cycle_id'], ['review_cycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_comment_review_cycle_id'), 'review_comment', ['review_cycle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_comment_review_cycle_id'), table_name='review_comment')
    op.drop_table('review_comment')
    op.drop_index(op.f('ix_review_cycle_tenant_id'), table_name='review_cycle')
    op.drop_index(op.f('ix_review_cycle_artefact_id'), table_name='review_cycle')
    op.drop_table('review_cycle')
    # ### end Alembic commands ###
