"""Pydantic request/response schemas.

Create schemas intentionally accept the exact payload shapes already sent
by `mcp_gateway_service`'s SAP Execution MCP tools (see
`app/mcp/tool_schemas.py` there) plus an optional `tenant_id` for callers
that supply it directly (e.g. future UI/admin usage). When `tenant_id` is
omitted, the route falls back to the `X-Tenant-Id` header, then `"default"`.
"""
from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict


# ---------------------------------------------------------------------------
# Packages
# ---------------------------------------------------------------------------
class SapPackageCreate(BaseModel):
    tenant_id: Optional[str] = None
    package_name: str
    description: str
    software_component: Optional[str] = "LOCAL"
    parent_package: Optional[str] = None
    transport_request: Optional[str] = None


class SapPackageRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    tenant_id: str
    package_name: str
    description: str
    software_component: str
    parent_package: Optional[str] = None
    transport_request: Optional[str] = None
    status: str
    created_at: Optional[datetime] = None


# ---------------------------------------------------------------------------
# Transports
# ---------------------------------------------------------------------------
class SapTransportCreate(BaseModel):
    tenant_id: Optional[str] = None
    description: str
    transport_type: Optional[str] = "workbench"
    target_system: Optional[str] = None
    owner: Optional[str] = None


class SapTransportRelease(BaseModel):
    transport_request: str


class SapTransportRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    tenant_id: str
    transport_request: str
    description: str
    transport_type: str
    target_system: Optional[str] = None
    owner: Optional[str] = None
    status: str
    released_at: Optional[datetime] = None
    created_at: Optional[datetime] = None


# ---------------------------------------------------------------------------
# Generated objects (generic / RAP / CDS / OData all share one table)
# ---------------------------------------------------------------------------
class GenerateObjectCreate(BaseModel):
    tenant_id: Optional[str] = None
    object_name: str
    object_type: str
    package: str
    transport_request: str
    description: Optional[str] = "Generated by SAP Execution MCP Gateway"
    source_code: Optional[str] = None


class GenerateRAPCreate(BaseModel):
    tenant_id: Optional[str] = None
    business_object_name: str
    package: str
    transport_request: str
    root_entity: str
    behavior_definition: Optional[str] = None
    projection_needed: Optional[bool] = True


class GenerateCDSCreate(BaseModel):
    tenant_id: Optional[str] = None
    view_name: str
    package: str
    transport_request: str
    ddl_source: str
    annotations: Optional[List[str]] = None


class GenerateODataCreate(BaseModel):
    tenant_id: Optional[str] = None
    service_name: str
    package: str
    transport_request: str
    odata_version: Optional[str] = "v4"
    entity_set: Optional[str] = None


class GeneratedObjectRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    tenant_id: str
    object_name: str
    object_type: str
    package: str
    transport_request: str
    description: Optional[str] = None
    source_code: Optional[str] = None
    extra: Optional[Dict[str, Any]] = None
    status: str
    created_at: Optional[datetime] = None


# ---------------------------------------------------------------------------
# Activation
# ---------------------------------------------------------------------------
class ActivationCreate(BaseModel):
    tenant_id: Optional[str] = None
    object_name: str
    object_type: str


class ActivationRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    tenant_id: str
    object_name: str
    object_type: str
    status: str
    activated_at: Optional[datetime] = None
    created_at: Optional[datetime] = None


# ---------------------------------------------------------------------------
# ATC
# ---------------------------------------------------------------------------
class AtcRunCreate(BaseModel):
    tenant_id: Optional[str] = None
    object_name: str
    object_type: str
    variant: Optional[str] = "DEFAULT"


class AtcRunRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    tenant_id: str
    object_name: str
    object_type: str
    variant: str
    status: str
    findings: List[Dict[str, Any]]
    created_at: Optional[datetime] = None


class AtcRemediationCreate(BaseModel):
    tenant_id: Optional[str] = None
    object_name: str
    object_type: str
    finding_ids: List[str]
    auto_apply: Optional[bool] = False


class AtcRemediationRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    tenant_id: str
    object_name: str
    object_type: str
    finding_ids: List[str]
    auto_apply: bool
    status: str
    remediated_at: Optional[datetime] = None
    created_at: Optional[datetime] = None


# ---------------------------------------------------------------------------
# Unit testing
# ---------------------------------------------------------------------------
class UnitTestRunCreate(BaseModel):
    tenant_id: Optional[str] = None
    object_name: str
    object_type: str
    test_classes: Optional[List[str]] = None


class UnitTestRunRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    tenant_id: str
    object_name: str
    object_type: str
    test_classes: Optional[List[str]] = None
    status: str
    results: Dict[str, Any]
    created_at: Optional[datetime] = None


# ---------------------------------------------------------------------------
# SAP Solution Architect Agent - execution planning
# ---------------------------------------------------------------------------
class ExecutionPlanCreate(BaseModel):
    tenant_id: Optional[str] = None
    technical_specification_id: str
    package_name: Optional[str] = None
    needs_cds: Optional[bool] = False
    needs_rap: Optional[bool] = False
    needs_odata: Optional[bool] = False
    object_names: Optional[List[str]] = None


class ExecutionPlanRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    tenant_id: str
    technical_specification_id: str
    package_name: Optional[str] = None
    transport_description: Optional[str] = None
    steps: List[Dict[str, Any]]
    status: str
    created_at: Optional[datetime] = None
