"""initial schema

Revision ID: c232a1d9e363
Revises: 
Create Date: 2026-07-20 15:36:48.067282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c232a1d9e363'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technical_specification',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('functional_specification_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('blob_uri', sa.Text(), nullable=True),
    sa.Column('regeneration_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['parent_version_id'], ['technical_specification.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_specification_functional_specification_id'), 'technical_specification', ['functional_specification_id'], unique=False)
    op.create_index(op.f('ix_technical_specification_tenant_id'), 'technical_specification', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technical_specification_tenant_id'), table_name='technical_specification')
    op.drop_index(op.f('ix_technical_specification_functional_specification_id'), table_name='technical_specification')
    op.drop_table('technical_specification')
    # ### end Alembic commands ###
