"""initial schema

Revision ID: 7bc68d9b425e
Revises: 
Create Date: 2026-07-20 15:36:47.024875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc68d9b425e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirement_set',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('transcript_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_set_tenant_id'), 'requirement_set', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_requirement_set_transcript_id'), 'requirement_set', ['transcript_id'], unique=False)
    op.create_table('business_rule',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requirement_set_id', sa.String(length=36), nullable=False),
    sa.Column('rule', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['requirement_set_id'], ['requirement_set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_rule_requirement_set_id'), 'business_rule', ['requirement_set_id'], unique=False)
    op.create_table('requirement',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requirement_set_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['requirement_set_id'], ['requirement_set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_requirement_set_id'), 'requirement', ['requirement_set_id'], unique=False)
    op.create_table('requirement_entity',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requirement_set_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['requirement_set_id'], ['requirement_set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_entity_requirement_set_id'), 'requirement_entity', ['requirement_set_id'], unique=False)
    op.create_table('requirement_risk',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requirement_set_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['requirement_set_id'], ['requirement_set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_risk_requirement_set_id'), 'requirement_risk', ['requirement_set_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requirement_risk_requirement_set_id'), table_name='requirement_risk')
    op.drop_table('requirement_risk')
    op.drop_index(op.f('ix_requirement_entity_requirement_set_id'), table_name='requirement_entity')
    op.drop_table('requirement_entity')
    op.drop_index(op.f('ix_requirement_requirement_set_id'), table_name='requirement')
    op.drop_table('requirement')
    op.drop_index(op.f('ix_business_rule_requirement_set_id'), table_name='business_rule')
    op.drop_table('business_rule')
    op.drop_index(op.f('ix_requirement_set_transcript_id'), table_name='requirement_set')
    op.drop_index(op.f('ix_requirement_set_tenant_id'), table_name='requirement_set')
    op.drop_table('requirement_set')
    # ### end Alembic commands ###
