"""initial schema

Revision ID: 530b98f85880
Revises: 
Create Date: 2026-07-20 15:36:51.204731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '530b98f85880'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_run',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('transcript_id', sa.String(length=36), nullable=False),
    sa.Column('current_state', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_run_tenant_id'), 'workflow_run', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workflow_run_transcript_id'), 'workflow_run', ['transcript_id'], unique=False)
    op.create_table('workflow_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=36), nullable=False),
    sa.Column('from_state', sa.String(length=64), nullable=True),
    sa.Column('to_state', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_event_workflow_run_id'), 'workflow_event', ['workflow_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_event_workflow_run_id'), table_name='workflow_event')
    op.drop_table('workflow_event')
    op.drop_index(op.f('ix_workflow_run_transcript_id'), table_name='workflow_run')
    op.drop_index(op.f('ix_workflow_run_tenant_id'), table_name='workflow_run')
    op.drop_table('workflow_run')
    # ### end Alembic commands ###
