"""initial schema

Revision ID: 0f05279f32aa
Revises: 
Create Date: 2026-07-20 15:36:46.490895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f05279f32aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_document',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('origin_uri', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('blob_uri', sa.Text(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_document_project_id'), 'source_document', ['project_id'], unique=False)
    op.create_index(op.f('ix_source_document_tenant_id'), 'source_document', ['tenant_id'], unique=False)
    op.create_table('transcript',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_document_id', sa.String(length=36), nullable=False),
    sa.Column('meeting_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('participants', sa.JSON(), nullable=False),
    sa.Column('parsed_format', sa.String(length=32), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('structured_content', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_source_document_id'), 'transcript', ['source_document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcript_source_document_id'), table_name='transcript')
    op.drop_table('transcript')
    op.drop_index(op.f('ix_source_document_tenant_id'), table_name='source_document')
    op.drop_index(op.f('ix_source_document_project_id'), table_name='source_document')
    op.drop_table('source_document')
    # ### end Alembic commands ###
