"""SAP ADT (ABAP Development Tools) REST API client.

Uses plain HTTP requests against ADT endpoints instead of PyRFC. Authentication
is intentionally stubbed out behind `get_adt_session()` so it can be swapped
for basic auth, SNC, or SSO cookie-based auth without touching call sites.
"""
from __future__ import annotations

import requests

from app.config import settings

ADT_XML_CONTENT_TYPE = "application/vnd.sap.adt.programs.programs.v2+xml"


def get_adt_session() -> requests.Session:
    """Return an authenticated `requests.Session` for calling ADT endpoints.

    TODO(auth): This is a stub. Wire up real authentication here:
      - basic:  session.auth = (settings.adt_username, settings.adt_password)
      - snc:    negotiate an SNC/X.509-backed session and attach the resulting
                cookie jar (e.g. MYSAPSSO2) to `session.cookies`.
    For now this only supports HTTP basic auth for local POC testing.
    """
    session = requests.Session()
    if settings.adt_auth_mode == "basic":
        session.auth = (settings.adt_username, settings.adt_password)
    elif settings.adt_auth_mode == "snc":
        # TODO: implement SNC-based session/cookie auth.
        raise NotImplementedError(
            "SNC auth is not implemented yet. Configure ADT_AUTH_MODE=basic "
            "for local testing, or implement get_adt_session() for SNC."
        )
    else:
        raise ValueError(f"Unsupported ADT_AUTH_MODE: {settings.adt_auth_mode}")

    session.headers.update({"Accept": "application/xml"})
    return session


def _csrf_token(session: requests.Session) -> str:
    """Fetch a CSRF token required by ADT for state-changing requests."""
    response = session.get(
        f"{settings.adt_base_url}/sap/bc/adt/programs/programs",
        params={"sap-client": settings.adt_sap_client},
        headers={"X-CSRF-Token": "Fetch"},
        timeout=30,
    )
    response.raise_for_status()
    return response.headers.get("X-CSRF-Token", "")


def create_adt_object(
    object_name: str,
    source_code: str,
    *,
    package: str | None = None,
    object_type: str = "PROG",
    description: str = "Generated by RAG POC pipeline",
) -> dict:
    """Create an ABAP object (program/report) via the ADT REST API as INACTIVE.

    This targets the /sap/bc/adt/programs/programs collection for simple
    reports. Extend `object_type`/endpoint handling to support classes via
    /sap/bc/adt/oo/classes if needed.

    Returns a dict describing the outcome; raises requests.HTTPError on
    non-2xx responses so callers/nodes can decide how to handle failures.
    """
    package = package or settings.adt_target_package
    session = get_adt_session()
    csrf_token = _csrf_token(session)

    create_payload = f"""<?xml version="1.0" encoding="UTF-8"?>
<program:abapProgram xmlns:adtcore="http://www.sap.com/adt/core"
    xmlns:program="http://www.sap.com/adt/programs/programs"
    adtcore:name="{object_name}"
    adtcore:type="{object_type}/P"
    adtcore:description="{description}"
    adtcore:masterLanguage="EN">
  <adtcore:packageRef adtcore:name="{package}"/>
</program:abapProgram>"""

    create_response = session.post(
        f"{settings.adt_base_url}/sap/bc/adt/programs/programs",
        params={"sap-client": settings.adt_sap_client},
        headers={
            "X-CSRF-Token": csrf_token,
            "Content-Type": "application/vnd.sap.adt.programs.programs.v2+xml",
        },
        data=create_payload,
        timeout=30,
    )
    create_response.raise_for_status()

    source_response = session.put(
        f"{settings.adt_base_url}/sap/bc/adt/programs/programs/{object_name}/source/main",
        # TODO: A real ADT client must first acquire an edit lock via
        # POST .../source/main?_action=LOCK (stateful session,
        # X-sap-adt-sessiontype: stateful) and pass the returned lockHandle
        # here. An empty lockHandle works against some sandbox systems but is
        # not a reliable/safe pattern — wire up the real lock/unlock flow
        # before using this against a shared development system.
        params={"sap-client": settings.adt_sap_client, "lockHandle": ""},
        headers={
            "X-CSRF-Token": csrf_token,
            "Content-Type": "text/plain; charset=utf-8",
        },
        data=source_code.encode("utf-8"),
        timeout=30,
    )
    source_response.raise_for_status()

    return {
        "object_name": object_name,
        "object_type": object_type,
        "package": package,
        "status_code": source_response.status_code,
        "inactive": True,
        "raw_response": source_response.text,
    }
