"""initial schema

Revision ID: a9f124079647
Revises: 
Create Date: 2026-07-20 15:36:49.626345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9f124079647'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log_entry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entry_entity_id'), 'audit_log_entry', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entry_entity_type'), 'audit_log_entry', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_entry_tenant_id'), 'audit_log_entry', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_entry_tenant_id'), table_name='audit_log_entry')
    op.drop_index(op.f('ix_audit_log_entry_entity_type'), table_name='audit_log_entry')
    op.drop_index(op.f('ix_audit_log_entry_entity_id'), table_name='audit_log_entry')
    op.drop_table('audit_log_entry')
    # ### end Alembic commands ###
