"""initial schema

Revision ID: 36a7f1d92587
Revises: 
Create Date: 2026-07-20 17:04:52.496861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36a7f1d92587'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('object_name', sa.String(length=128), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activation_object_name'), 'activation', ['object_name'], unique=False)
    op.create_index(op.f('ix_activation_tenant_id'), 'activation', ['tenant_id'], unique=False)
    op.create_table('atc_remediation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('object_name', sa.String(length=128), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=False),
    sa.Column('finding_ids', sa.JSON(), nullable=False),
    sa.Column('auto_apply', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('remediated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atc_remediation_object_name'), 'atc_remediation', ['object_name'], unique=False)
    op.create_index(op.f('ix_atc_remediation_tenant_id'), 'atc_remediation', ['tenant_id'], unique=False)
    op.create_table('atc_run',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('object_name', sa.String(length=128), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=False),
    sa.Column('variant', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atc_run_object_name'), 'atc_run', ['object_name'], unique=False)
    op.create_index(op.f('ix_atc_run_tenant_id'), 'atc_run', ['tenant_id'], unique=False)
    op.create_table('execution_plan',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('technical_specification_id', sa.String(length=36), nullable=False),
    sa.Column('package_name', sa.String(length=128), nullable=True),
    sa.Column('transport_description', sa.Text(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_plan_technical_specification_id'), 'execution_plan', ['technical_specification_id'], unique=False)
    op.create_index(op.f('ix_execution_plan_tenant_id'), 'execution_plan', ['tenant_id'], unique=False)
    op.create_table('generated_object',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('object_name', sa.String(length=128), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=False),
    sa.Column('package', sa.String(length=128), nullable=False),
    sa.Column('transport_request', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_code', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_object_object_name'), 'generated_object', ['object_name'], unique=False)
    op.create_index(op.f('ix_generated_object_object_type'), 'generated_object', ['object_type'], unique=False)
    op.create_index(op.f('ix_generated_object_tenant_id'), 'generated_object', ['tenant_id'], unique=False)
    op.create_table('sap_package',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('package_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('software_component', sa.String(length=64), nullable=False),
    sa.Column('parent_package', sa.String(length=128), nullable=True),
    sa.Column('transport_request', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sap_package_package_name'), 'sap_package', ['package_name'], unique=False)
    op.create_index(op.f('ix_sap_package_tenant_id'), 'sap_package', ['tenant_id'], unique=False)
    op.create_table('sap_transport',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('transport_request', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('transport_type', sa.String(length=16), nullable=False),
    sa.Column('target_system', sa.String(length=64), nullable=True),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sap_transport_tenant_id'), 'sap_transport', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sap_transport_transport_request'), 'sap_transport', ['transport_request'], unique=True)
    op.create_table('unit_test_run',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('object_name', sa.String(length=128), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=False),
    sa.Column('test_classes', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_test_run_object_name'), 'unit_test_run', ['object_name'], unique=False)
    op.create_index(op.f('ix_unit_test_run_tenant_id'), 'unit_test_run', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_test_run_tenant_id'), table_name='unit_test_run')
    op.drop_index(op.f('ix_unit_test_run_object_name'), table_name='unit_test_run')
    op.drop_table('unit_test_run')
    op.drop_index(op.f('ix_sap_transport_transport_request'), table_name='sap_transport')
    op.drop_index(op.f('ix_sap_transport_tenant_id'), table_name='sap_transport')
    op.drop_table('sap_transport')
    op.drop_index(op.f('ix_sap_package_tenant_id'), table_name='sap_package')
    op.drop_index(op.f('ix_sap_package_package_name'), table_name='sap_package')
    op.drop_table('sap_package')
    op.drop_index(op.f('ix_generated_object_tenant_id'), table_name='generated_object')
    op.drop_index(op.f('ix_generated_object_object_type'), table_name='generated_object')
    op.drop_index(op.f('ix_generated_object_object_name'), table_name='generated_object')
    op.drop_table('generated_object')
    op.drop_index(op.f('ix_execution_plan_tenant_id'), table_name='execution_plan')
    op.drop_index(op.f('ix_execution_plan_technical_specification_id'), table_name='execution_plan')
    op.drop_table('execution_plan')
    op.drop_index(op.f('ix_atc_run_tenant_id'), table_name='atc_run')
    op.drop_index(op.f('ix_atc_run_object_name'), table_name='atc_run')
    op.drop_table('atc_run')
    op.drop_index(op.f('ix_atc_remediation_tenant_id'), table_name='atc_remediation')
    op.drop_index(op.f('ix_atc_remediation_object_name'), table_name='atc_remediation')
    op.drop_table('atc_remediation')
    op.drop_index(op.f('ix_activation_tenant_id'), table_name='activation')
    op.drop_index(op.f('ix_activation_object_name'), table_name='activation')
    op.drop_table('activation')
    # ### end Alembic commands ###
