import { http, HttpResponse } from 'msw';
import { serviceBaseUrls } from '../../api/config';

const base = serviceBaseUrls;

export const sampleTranscript = {
  id: 't-1',
  source_document_id: 'sd-1',
  meeting_date: '2024-01-01T10:00:00Z',
  participants: ['Alice', 'Bob'],
  parsed_format: 'TEXT',
  raw_text: 'Sample transcript text',
  structured_content: null,
  created_at: '2024-01-01T10:05:00Z',
};

export const sampleRequirementSet = {
  id: 'rs-1',
  tenant_id: 'tenant-1',
  transcript_id: 't-1',
  version: 1,
  status: 'DRAFT',
  created_at: '2024-01-01T11:00:00Z',
};

export const sampleRequirement = {
  id: 'req-1',
  requirement_set_id: 'rs-1',
  type: 'FUNCTIONAL',
  title: 'Sample requirement',
  description: 'Requirement description',
  priority: 'HIGH',
  created_at: '2024-01-01T11:05:00Z',
};

export const sampleFs = {
  id: 'fs-1',
  tenant_id: 'tenant-1',
  requirement_set_id: 'rs-1',
  template_id: 'tpl-1',
  version: 1,
  status: 'DRAFT',
  content: {},
  regeneration_count: 0,
  created_at: '2024-01-01T12:00:00Z',
};

export const sampleTs = {
  id: 'ts-1',
  tenant_id: 'tenant-1',
  functional_specification_id: 'fs-1',
  template_id: 'tpl-2',
  version: 1,
  status: 'DRAFT',
  content: {},
  regeneration_count: 0,
  created_at: '2024-01-01T13:00:00Z',
};

export const sampleReviewCycle = {
  id: 'rc-1',
  tenant_id: 'tenant-1',
  artefact_type: 'FS',
  artefact_id: 'fs-1',
  gate: 'FS_GATE',
  status: 'PENDING',
  opened_at: '2024-01-01T12:30:00Z',
  closed_at: null,
};

export const sampleAuditEntry = {
  id: 'audit-1',
  tenant_id: 'tenant-1',
  entity_type: 'transcript',
  entity_id: 't-1',
  action: 'CREATE',
  actor: 'system',
  before: null,
  after: null,
  occurred_at: '2024-01-01T10:05:00Z',
};

export const sampleWorkflowRun = {
  id: 'wf-1',
  tenant_id: 'tenant-1',
  transcript_id: 't-1',
  current_state: 'IN_PROGRESS',
  started_at: '2024-01-01T10:00:00Z',
  completed_at: null,
};

export const sampleWorkflowEvent = {
  id: 'we-1',
  workflow_run_id: 'wf-1',
  from_state: 'STARTED',
  to_state: 'IN_PROGRESS',
  actor: 'system',
  occurred_at: '2024-01-01T10:01:00Z',
};

export const sampleKnowledgeSource = {
  id: 'ks-1',
  tenant_id: 'tenant-1',
  source_type: 'SAP_HELP',
  uri: 'https://help.sap.com/example',
  last_indexed_at: '2024-01-01T09:00:00Z',
  is_dead_link: false,
};

export const sampleKnowledgeChunk = {
  id: 'kc-1',
  knowledge_source_id: 'ks-1',
  chunk_index: 0,
  text: 'Sample indexed chunk text',
  vector_id: 'vec-1',
  created_at: '2024-01-01T09:05:00Z',
};

export const sampleTenant = {
  id: 'tenant-1',
  name: 'Acme Corp',
  entra_tenant_id: 'entra-1',
  tier: 'SHARED',
  status: 'ACTIVE',
  created_at: '2024-01-01T08:00:00Z',
};

export const sampleProject = {
  id: 'proj-1',
  tenant_id: 'tenant-1',
  name: 'S/4HANA Rollout',
  sap_execution_repo_url: 'https://repo.example/sap',
  created_at: '2024-01-01T08:05:00Z',
};

export const sampleDocumentTemplate = {
  id: 'tpl-1',
  tenant_id: 'tenant-1',
  type: 'FS',
  name: 'Default FS Template',
  version: 1,
  schema_: {},
  is_active: true,
  created_at: '2024-01-01T08:10:00Z',
};

export const sampleUser = {
  id: 'user-1',
  tenant_id: 'tenant-1',
  email: 'user@example.com',
  display_name: 'Sample User',
  role: 'CONTRIBUTOR',
  is_active: true,
  created_at: '2024-01-01T08:15:00Z',
};

export const sampleReviewDecision = {
  id: 'rd-1',
  review_cycle_id: 'rc-1',
  decided_by: 'user-1',
  decision: 'APPROVED',
  decided_at: '2024-01-01T14:00:00Z',
};

export const sampleSapPackage = {
  id: 'pkg-1',
  tenant_id: 'tenant-1',
  technical_specification_id: 'ts-1',
  version: 1,
  status: 'PUBLISHED',
  payload: {},
  sap_execution_repo_ref: 'refs/heads/main',
  published_at: '2024-01-01T15:00:00Z',
};

export const sampleExecutionSapPackage = {
  id: 'exec-pkg-1',
  tenant_id: 'tenant-1',
  package_name: 'ZRAG_POC',
  description: 'POC package',
  software_component: 'LOCAL',
  parent_package: null,
  transport_request: null,
  status: 'CREATED',
  created_at: '2024-01-01T16:00:00Z',
};

export const sampleSapTransport = {
  id: 'transport-1',
  tenant_id: 'tenant-1',
  transport_request: 'TRABCD1234',
  description: 'Feature transport',
  transport_type: 'workbench',
  target_system: null,
  owner: null,
  status: 'MODIFIABLE',
  released_at: null,
  created_at: '2024-01-01T16:05:00Z',
};

export const sampleGeneratedObject = {
  id: 'obj-1',
  tenant_id: 'tenant-1',
  object_name: 'ZPROGRAM',
  object_type: 'PROGRAM',
  package: 'ZRAG_POC',
  transport_request: 'TRABCD1234',
  description: 'Generated by SAP Execution MCP Gateway',
  source_code: 'REPORT zprogram.',
  extra: null,
  status: 'INACTIVE',
  created_at: '2024-01-01T16:10:00Z',
};

export const sampleActivation = {
  id: 'act-1',
  tenant_id: 'tenant-1',
  object_name: 'ZPROGRAM',
  object_type: 'PROGRAM',
  status: 'ACTIVATED',
  activated_at: '2024-01-01T16:15:00Z',
  created_at: '2024-01-01T16:15:00Z',
};

export const sampleAtcRun = {
  id: 'atc-run-1',
  tenant_id: 'tenant-1',
  object_name: 'ZPROGRAM',
  object_type: 'PROGRAM',
  variant: 'DEFAULT',
  status: 'COMPLETED',
  findings: [],
  created_at: '2024-01-01T16:20:00Z',
};

export const sampleAtcRemediation = {
  id: 'atc-rem-1',
  tenant_id: 'tenant-1',
  object_name: 'ZPROGRAM',
  object_type: 'PROGRAM',
  finding_ids: ['F1'],
  auto_apply: true,
  status: 'APPLIED',
  remediated_at: '2024-01-01T16:25:00Z',
  created_at: '2024-01-01T16:25:00Z',
};

export const sampleExecutionPlan = {
  id: 'plan-1',
  tenant_id: 'tenant-1',
  technical_specification_id: 'ts-1',
  package_name: 'ZRAG_POC',
  transport_description: null,
  steps: [{ order: 1, tool: 'create_package' }],
  status: 'PROPOSED',
  created_at: '2024-01-01T16:30:00Z',
};

export const handlers = [
  http.get(`${base.transcript}/transcripts`, () => HttpResponse.json([sampleTranscript])),
  http.get(`${base.transcript}/source-documents`, () => HttpResponse.json([])),
  http.get(`${base.transcript}/health`.replace('/api/v1', ''), () =>
    HttpResponse.json({ status: 'ok', service: 'transcript_service' }),
  ),

  http.get(`${base.documentExtraction}/requirement-sets`, () => HttpResponse.json([sampleRequirementSet])),
  http.get(`${base.documentExtraction}/requirements`, () => HttpResponse.json([sampleRequirement])),
  http.get(`${base.documentExtraction}/health`.replace('/api/v1', ''), () =>
    HttpResponse.json({ status: 'ok', service: 'document_extraction_service' }),
  ),

  http.get(`${base.fs}/functional-specifications`, () => HttpResponse.json([sampleFs])),
  http.get(`${base.fs}/document-templates`, () => HttpResponse.json([sampleDocumentTemplate])),
  http.get(`${base.fs}/health`.replace('/api/v1', ''), () =>
    HttpResponse.json({ status: 'ok', service: 'fs_service' }),
  ),

  http.get(`${base.ts}/technical-specifications`, () => HttpResponse.json([sampleTs])),
  http.get(`${base.ts}/health`.replace('/api/v1', ''), () =>
    HttpResponse.json({ status: 'ok', service: 'ts_service' }),
  ),

  http.get(`${base.review}/review-cycles`, () => HttpResponse.json([sampleReviewCycle])),
  http.get(`${base.review}/review-comments`, () => HttpResponse.json([])),
  http.get(`${base.review}/health`.replace('/api/v1', ''), () =>
    HttpResponse.json({ status: 'ok', service: 'review_service' }),
  ),

  http.get(`${base.approval}/review-decisions`, () => HttpResponse.json([sampleReviewDecision])),
  http.get(`${base.approval}/sap-execution-packages`, () => HttpResponse.json([sampleSapPackage])),
  http.get(`${base.approval}/health`.replace('/api/v1', ''), () =>
    HttpResponse.json({ status: 'ok', service: 'approval_service' }),
  ),

  http.get(`${base.audit}/audit-log-entries`, () => HttpResponse.json([sampleAuditEntry])),
  http.get(`${base.audit}/health`.replace('/api/v1', ''), () =>
    HttpResponse.json({ status: 'ok', service: 'audit_service' }),
  ),

  http.get(`${base.rag}/knowledge-sources`, () => HttpResponse.json([sampleKnowledgeSource])),
  http.get(`${base.rag}/knowledge-chunks`, () => HttpResponse.json([sampleKnowledgeChunk])),
  http.get(`${base.rag}/health`.replace('/api/v1', ''), () =>
    HttpResponse.json({ status: 'ok', service: 'rag_service' }),
  ),

  http.get(`${base.user}/tenants`, () => HttpResponse.json([sampleTenant])),
  http.get(`${base.user}/projects`, () => HttpResponse.json([sampleProject])),
  http.get(`${base.user}/users`, () => HttpResponse.json([sampleUser])),
  http.get(`${base.user}/health`.replace('/api/v1', ''), () =>
    HttpResponse.json({ status: 'ok', service: 'user_service' }),
  ),

  http.get(`${base.workflow}/workflow-runs`, () => HttpResponse.json([sampleWorkflowRun])),
  http.get(`${base.workflow}/workflow-events`, () => HttpResponse.json([sampleWorkflowEvent])),
  http.get(`${base.workflow}/health`.replace('/api/v1', ''), () =>
    HttpResponse.json({ status: 'ok', service: 'workflow_service' }),
  ),

  http.post(`${base.mcpGateway}/tools/search_documents`, () =>
    HttpResponse.json({
      results: [
        {
          chunk_id: 'kc-1',
          source_uri: 'ks-1',
          source_type: 'SAP_HELP',
          text: 'Sample indexed chunk text',
          score: 0.87,
          is_dead_link: false,
        },
      ],
    }),
  ),
  http.get(`${base.mcpGateway}/tools/list_sources`, () =>
    HttpResponse.json({ sources: [sampleKnowledgeSource] }),
  ),
  http.get(`${base.mcpGateway}/tools/list_active_runs`, () => HttpResponse.json([sampleWorkflowRun])),
  http.get(`${base.mcpGateway}/health`.replace('/api/v1', ''), () =>
    HttpResponse.json({ status: 'ok', service: 'mcp_gateway_service' }),
  ),

  http.get(`${base.sapExecution}/packages`, () => HttpResponse.json([sampleExecutionSapPackage])),
  http.get(`${base.sapExecution}/transports`, () => HttpResponse.json([sampleSapTransport])),
  http.get(`${base.sapExecution}/objects`, () => HttpResponse.json([sampleGeneratedObject])),
  http.get(`${base.sapExecution}/activations`, () => HttpResponse.json([sampleActivation])),
  http.get(`${base.sapExecution}/atc-runs`, () => HttpResponse.json([sampleAtcRun])),
  http.get(`${base.sapExecution}/atc-remediations`, () => HttpResponse.json([sampleAtcRemediation])),
  http.get(`${base.sapExecution}/architect/plans`, () => HttpResponse.json([sampleExecutionPlan])),
  http.get(`${base.sapExecution}/health`.replace('/api/v1', ''), () =>
    HttpResponse.json({ status: 'ok', service: 'sap_execution_service' }),
  ),
];
