"""Pydantic input schemas for SAP Execution MCP tools."""
from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class CreatePackageInput(BaseModel):
    package_name: str
    description: str
    software_component: str = "LOCAL"
    parent_package: Optional[str] = None
    transport_request: Optional[str] = None


class CreateTransportInput(BaseModel):
    description: str
    transport_type: str = Field(default="workbench", description="workbench|customizing")
    target_system: Optional[str] = None
    owner: Optional[str] = None


class ReleaseTransportInput(BaseModel):
    transport_request: str


class GenerateObjectInput(BaseModel):
    object_name: str
    object_type: str
    package: str
    transport_request: str
    description: str = "Generated by SAP Execution MCP Gateway"
    source_code: Optional[str] = None


class GenerateRAPInput(BaseModel):
    business_object_name: str
    package: str
    transport_request: str
    root_entity: str
    behavior_definition: Optional[str] = None
    projection_needed: bool = True


class GenerateCDSInput(BaseModel):
    view_name: str
    package: str
    transport_request: str
    ddl_source: str
    annotations: Optional[List[str]] = None


class GenerateODataInput(BaseModel):
    service_name: str
    package: str
    transport_request: str
    odata_version: str = Field(default="v4", description="v2|v4")
    entity_set: Optional[str] = None


class ActivateObjectInput(BaseModel):
    object_name: str
    object_type: str


class RunUnitTestsInput(BaseModel):
    object_name: str
    object_type: str
    test_classes: Optional[List[str]] = None


class RunATCInput(BaseModel):
    object_name: str
    object_type: str
    variant: str = "DEFAULT"


class RemediateATCInput(BaseModel):
    object_name: str
    object_type: str
    finding_ids: List[str]
    auto_apply: bool = False
